version: "3.1"

services:
  worker-large-4:
    build:
      context: ../base
      dockerfile: Dockerfile
    volumes:
      - /gpfs/mskmind_ess/data/:/gpfs/mskmind_ess/data/
    image: mskmind/dask
    hostname: dask-worker
    networks:
      - dask-network
    command: ["dask-worker", "--nprocs", "8", "--nthreads", "1", "--memory-limit", "64GB", "--resources", "size=64", "tcp://scheduler:8786"]

  worker-medium-8:
    build:
      context: ../base
      dockerfile: Dockerfile
    volumes:
      - /gpfs/mskmind_ess/data/:/gpfs/mskmind_ess/data/
    image: mskmind/dask
    hostname: dask-worker
    networks:
      - dask-network
    command: ["dask-worker", "--nprocs", "12", "--nthreads", "1", "--memory-limit", "32GB", "--resources", "size=32", "tcp://scheduler:8786"]

  worker-small-16:
    build:
      context: ../base
      dockerfile: Dockerfile
    volumes:
      - /gpfs/mskmind_ess/data/:/gpfs/mskmind_ess/data/
    image: mskmind/dask
    hostname: dask-worker
    networks:
      - dask-network
    command: ["dask-worker", "--nprocs", "16", "--nthreads", "1", "--memory-limit", "16GB", "--resources", "size=16", "tcp://scheduler:8786"]

networks:
  dask-network:
     external: true      
