version: "3.1"

services:
  job-worker:
    build:
      context: ../base
      dockerfile: Dockerfile
    volumes:
      - /gpfs/mskmind_ess/data/:/gpfs/mskmind_ess/data/
    image: mskmind/dask
    hostname: dask-worker
    networks:
      - dask-network
    command: ["dask-worker", "--nprocs", "4", "--nthreads", "1", "tcp://job-scheduler:8786"]

  task-worker:
    build:
      context: ../base
      dockerfile: Dockerfile
    volumes:
      - /gpfs/mskmind_ess/data/:/gpfs/mskmind_ess/data/
    image: mskmind/dask
    hostname: dask-worker
    networks:
      - dask-network
    command: ["dask-worker", "--nprocs", "4", "--nthreads", "1", "tcp://task-scheduler:8788"]

networks:
  dask-network:
     external: true      
